### ISSUE TITLE
SSL Support?

### ISSUE THREAD

**Issue by ragymorkos** [Kai-Bailey/WebSock#1]
Hi,

This is a great framework! I'm wondering if there's SSL support built in? The [API webpage](https://websock.readthedocs.io/en/latest/) is broken, and I couldn't see anything related to SSL when I looked at the code.

Thanks,
Ragy

**Comment by Kai-Bailey** [comment]
Hi Ragy!

Sorry for the late reply. Unfortunately, WebSock does not have SSL support. I will take a look into the API webpage!
